### ISSUE TITLE
How can I reproduce the reported results.

### ISSUE THREAD

**Issue by mingyuShin** [EdwardLeeLPZ/PowerBEV#9]
Hello! 
I have another question. I trained a model from scratch with a batch size of 8 on a single A100 80GB GPU. 
I conducted the training twice, but in both instances, the Volumetric Panoptic Quality (VPQ) was lower than the performance reported in the paper. Could you tell me how I can reproduce the results?

VPQ: 30.64(first), 30.29(second)

And how can I train the static model?

![image](https://github.com/EdwardLeeLPZ/PowerBEV/assets/97519197/0250a6ab-2713-45fe-ada9-8619172bf41d)

```
TAG: 'powerbev'

GPUS: [0]

BATCHSIZE: 8
PRECISION: 16

LIFT:
  # Long
  X_BOUND: [-50.0, 50.0, 0.5]  # Forward
  Y_BOUND: [-50.0, 50.0, 0.5]  # Sides

  # # Short
  # X_BOUND: [-15.0, 15.0, 0.15]  # Forward
  # Y_BOUND: [-15.0, 15.0, 0.15]  # Sides

MODEL:
  BN_MOMENTUM: 0.05

N_WORKERS: 16
VIS_INTERVAL: 100
```
